services:
  backend:
    container_name: backend
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://admin:adminpassword@mongodb:27017/
      - PORT=5000
      - SECRET_KEY=d4c3a9b2e5f7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3
    depends_on:
      - mongodb
  
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    volumes:
      - ~/notedb_data:/data/db
    
  proxy:
    container_name: proxy
    build:
      context: ./Frontend/notes-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
