services:
  backend:
    container_name: backend
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=${MONGO_URL}
      - PORT=5000
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - mongodb
  
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    
  proxy:
    container_name: proxy
    build:
      context: ./Frontend/notes-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
